version: '3.8'

services:
  springboot:
    image: lkh8033/nextlevel-springboot:latest
    container_name: springboot
    ports:
      - "8080:8080"
    volumes:
      - ${PROJECT_DIR}/.env:/app/.env
      - ${PROJECT_DIR}/img:/app/img
    command: ["java", "-jar", "/app/app.jar", "--spring.profiles.active=prod"]
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: lkh8033/nextlevel-nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${PROJECT_DIR}/nginx.conf:/etc/nginx/nginx.conf
      - ${PROJECT_DIR}/img:/usr/share/nginx/html/img
    depends_on:
      - springboot
    networks:
      - app-network

  mysql:
    image: lkh8033/nextlevel-mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
