version: '3.8'

services:
  springboot:
    image: lkh8033/nextlevel-springboot:latest
    container_name: springboot
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/application-prod.yml:/app/application-prod.yml
      - /home/ubuntu/img:/app/img
    command: ["java", "-jar", "/app/app.jar", "--spring.profiles.active=prod", "--spring.config.additional-location=file:/app/application-prod.yml"]
    networks:
      - app-network

  nginx:
    image: lkh8033/nextlevel-nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/springboot.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/img:/usr/share/nginx/html/img
    depends_on:
      - springboot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
